USE COMP2003HK_GROUP_B
GO

INSERT INTO gp.Trees VALUES
    ('African Tulip Tree', 
    '',
    'Spathodea campanulata P. Beauv.',
    '306',
    'Exotic',
    0, 0, 0, 0,
    1, 5, 3, 11,
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=4521'
    ),
    ('Chinese Albizia', 
    'Albizia stipulata (DC.) Boivin',
    'Albizia chinensis (Osbeck) Merr.',
    '183',
    'Native',
    0, 0, 0, 0,
    1, 5, 6, 12,
    'This is an evergreen tree of the Mimosaceae family.  Leaves are double compound, with glands.  Pale white flowers occur in clusters at the end of branches.  Numerous long white stamens make it look like a powder-puff flower.  It favors higher temperatures and humidity, while not being too choosy for soil conditions.  It grows best nonetheless in well-drained red and sandy soil.  It also prefers sunshine to shade, and sheltered to wind-exposed area.  Capable of rapid growth, it has dense leaves and branches, providing good shade.  The wood is brown in color, soft in texture; bark contains tannin.  Three native Albizia Chinensis exist near the Academic Building.  They are older than the University itself.'
    ),
    ('Asoka, Common Saraca', 
    '',
    'Saraca dives Pierre',
    '184',
    'Exotic',
    0, 0, 0, 0,
    4, 5, 7, 10,
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=4547'
    ),
    ('White Azalea', 
    '',
    'Rhododendron mucronatum (Blume) G. Don',
    '147',
    'Exotic',
    1, 0, 0, 0,
    3, 4, -1, -1,
    'Early spring finds vigorous blossoms in front of the Franklin Building.  In this showy display of a month or two, white, pink and purplish-red Azaleas bloom all at once with full vitality.  It is the perfect spot to enjoy flowers and take photos.  Variations of Azalea are cultivar species.'
    ),
    ('Bald Cypress, Deciduous Cypress', 
    '',
    'Taxodium distichum (L.) Rich.',
    'G005',
    'Exotic',
    0, 0, 0, 0,
    3, 4, 7, 10,
    'Alongside Lake Ad Excellentiam grow a line of tall trees, including the Water Pine, Bald Cypress and the Pond Cypress.  All belonging to the Taxodiaceae family, they have in common woody "knee" roots that project from the ground or water, allowing them to live in aquatic habitats.  The Bald Cypress seems to have feather-like compound leaves, but when examining in detail, they are in fact elongated small leaves arranged in two ranks along a branchlet.  In its scientific name, "Distichum" exactly means two rows.  The Bald Cypress is an imported species from North America.  It gives a fantastic view of yellow fall leaves.'
    ),
    ('Batavia Cinnamon, Cinnamon Tree',
    '',
    'Cinnamomum burmannii (Nees & T. Nees) Blume',
    '017',
    'Native',
    0, 0, 0, 0,
    3, 4, 10, 11,
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=6132'
    ),
    ('Brisbane Box', 
    'Tristania conferta R. Br.',
    'Lophostemon confertus (R. Br.) Peter G. Wilson & J. T. Waterh.',
    '199',
    'Exotic',
    0, 0, 0, 0,
    5, 7, 8, 9,
    'The Taiwan Acacia and Brisbane Box can be counted as two of the most common exotic trees in Hong Kong.  Native to Australia, it has dark green leaves with smooth edges; opposite when young, alternate when mature, they rotate and aggregate on branch tops.  White flowers with numerous inconspicuous stamens appear in 5 feather-like bunches in summer.  Fruits are born in autumn as bell-shaped woody capsules that can be 2 cm large.'
    ),
    ('Buddhist Pine, Kusamaki', 
    '',
    'Podocarpus macrophyllus (Thunb.) Sweet',
    'G008',
    'Native',
    0, 0, 0, 0,
    4, 5, 8, 9,
    'This plant grows at a slow speed.  On the sturdy stem are strong and horizontal branches.  Evergreen with alternate, spirally arranged leaves, acute at both ends, the Buddhist pine has high ornamental values.  They used to exist in abundance at the east coast of the territory.  Yet superstition turned them into vastly profitable commercial goods.  With increasing illegally logging, they are now endangered species.  Also a dioecious plant, among the row of Buddhist Pines grown in New Asia College, some flowers in spring bear small globose fruits with a purplish fleshy receptacle.  The plant’s form of a human figure gives it the common name of "Buddhist Pine".'
    ),
    ('Burmese Rosewood', 
    '',
    'Pterocarpus indicus Willd.',
    '185',
    'Exotic',
    0, 0, 0, 0,
    2, 8, 11, 11,
    'A large deciduous tree, it can grow up to a height of 40 meters.  The growth is slow and one tree can age more than a hundred years.  The drooping twigs form a broad canopy of a bell shape, making the plant an excellent pavement tree.  The timber is of high quality, hard and reddish, often used to make instruments and furniture.  Flowering in summer, the slightly fragranced bloom is arranged in raceme inflorescence.  Spherical fruits are like "sunnyside-up" fried eggs, dark brown in color, usually possessing one stone inside, also dark brown in color.  On CUHK campus, one Burmese Rosewood is located in front of University Health Centre on the eastern campus; a taller one can be found on the western campus near where the stele of "Chinese University of Hong Kong" lies.'
    ),
    ('Camel"s Foot Tree', 
    '',
    'Bauhinia variegata L.',
    '184',
    'Exotic',
    0, 0, 0, 0,
    3, 3, 4, 4,
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=8337'
    ),
    ('Camptotheca', 
    '',
    'Camptotheca acuminata Decne.',
    '207',
    'Exotic',
    0, 0, 0, 0,
    5, 7, 9, 9,
    'Native to China, this deciduous tree has spherical flowers and fruits.  Fruits, samara-like, cluster in globose heads.  Leaves are oblong-elliptic, papery and slightly puberulous (hairy).  The whole tree contains camptothecin, which is a primary material for anti-cancer and leukemia treatments.  It is presently a species under national protection (category II).'
    ),
    ('Candlenut Tree, Common Aleurites', 
    '',
    'Aleurites moluccana (L.) Willd.',
    '237',
    'Exotic',
    0, 0, 0, 0,
    4, 10, 10, 12,
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=8135'
    ),
    ('Carambola', 
    '',
    'Averrhoa carambola L.',
    '268',
    'Exotic',
    0, 0, 0, 0,
    5, 8, 9, 12,
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=8282'
    ),
    ('Cerbera, Sea Mango', 
    '',
    'Cerbera manghas L.',
    '278',
    'Native',
    0, 0, 0, 0,
    4, 11, 7, 12,
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=4069'
    ),
    ('Chinese Alangium', 
    '',
    'Alangium chinense (Lour.) Harms',
    '206',
    'Native',
    0, 0, 0, 0,
    5, 7, 7, 11,
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=3369'
    )
;