INSERT INTO trees (tree_name_en, tree_name_cn, tree_alias, 
                    scientific_name, family_code, ecologic,
                    cap_96, cap_586, hk_rare, cn_rare, flowering, fruit, tree_desc_en, tree_desc_cn,
                    tree_image) VALUES
    ('African Tulip Tree', '火焰樹（火焰木）',
    '',
    'Spathodea campanulata P. Beauv.',
    '306',
    'Exotic',
    0, 0, 0, 0,
    '111110000000',
    '001111111110',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=4521',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=4521',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FAfrican%20Tulip%20Tree.jpeg?alt=media&token=b0548a37-4f85-4124-b712-85d363c99894'
    ),
    ('Chinese Albizia', '楹樹',
    'Albizia stipulata (DC.) Boivin',
    'Albizia chinensis (Osbeck) Merr.',
    '183',
    'Native',
    0, 0, 0, 0,
    '111110000000',
    '000001111111',
    'This is an evergreen tree of the Mimosaceae family.  Leaves are double compound, with glands.  Pale white flowers occur in clusters at the end of branches.  Numerous long white stamens make it look like a powder-puff flower.  It favors higher temperatures and humidity, while not being too choosy for soil conditions.  It grows best nonetheless in well-drained red and sandy soil.  It also prefers sunshine to shade, and sheltered to wind-exposed area.  Capable of rapid growth, it has dense leaves and branches, providing good shade.  The wood is brown in color, soft in texture; bark contains tannin.  Three native Albizia Chinensis exist near the Academic Building.  They are older than the University itself.',
    '屬含羞草科常綠喬木，二回羽狀復葉，葉有腺體，頂生圓錐花序，花淡白。喜高溫多濕，對土壤要求不嚴，在適濕排水良好的紅壤及砂土能生長良好，愛光，不耐陰，抗風力弱，生長迅速，枝葉茂盛，適為蔭蔽樹；木材褐色，質柔軟，樹皮含單寧。大學本部，近教研樓有三棵大楹樹，是原生樹種，樹齡比大學還高，列入香港古樹名目冊。',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FChinese%20Albizia.jpeg?alt=media&token=4db961fa-0770-4ff4-8e0a-825345816b1c'
    ),
    ('Asoka, Common Saraca', '中國無憂花',
    '',
    'Saraca dives Pierre',
    '184',
    'Exotic',
    0, 0, 0, 0,
    '000110000000',
    '000000111100',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=4547',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=4547',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FAsoka.jpeg?alt=media&token=957c52bd-29d0-4a11-bb4b-b0b5f1b80477'
    ),
    ('White Azalea', '白杜鵑',
    '',
    'Rhododendron mucronatum (Blume) G. Don',
    '147',
    'Exotic',
    1, 0, 0, 0,
    '001100000000',
    '000000000000',
    'Early spring finds vigorous blossoms in front of the Franklin Building.  In this showy display of a month or two, white, pink and purplish-red Azaleas bloom all at once with full vitality.  It is the perfect spot to enjoy flowers and take photos.  Variations of Azalea are cultivar species.',
    '范克廉樓外初春繁花似錦，白色，粉紅色，紫紅色杜鵑盛開，為賞花和攝影的上佳地點。各種杜鵑均為栽培品種。',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FWhite%20Azalea.jpeg?alt=media&token=9f84a4d0-7382-4d27-9eae-1b315d810022'
    ),
    ('Bald Cypress, Deciduous Cypress', '落羽杉',
    '',
    'Taxodium distichum (L.) Rich.',
    'G005',
    'Exotic',
    0, 0, 0, 0,
    '001100000000',
    '000000111100',
    'Alongside Lake Ad Excellentiam grow a line of tall trees, including the Water Pine, Bald Cypress and the Pond Cypress.  All belonging to the Taxodiaceae family, they have in common woody "knee" roots that project from the ground or water, allowing them to live in aquatic habitats.  The Bald Cypress seems to have feather-like compound leaves, but when examining in detail, they are in fact elongated small leaves arranged in two ranks along a branchlet.  In its scientific name, "Distichum" exactly means two rows.  The Bald Cypress is an imported species from North America.  It gives a fantastic view of yellow fall leaves.',
    '未圓湖邊一行高大的喬木，有水松，落羽松，和池杉，三種同屬於杉科，樹幹基部都具膝狀呼吸根，以適應水生環境。落羽松雖名為松，與松無關。落羽松葉片表面看似複葉，如一片羽毛，細看是長條形的小葉，在小枝兩邊排成兩行，而學名中的 distichum，即是兩列的意思。北美引種的大樹, 秋天可賞黃褐色落葉。',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FBald%20Cypress.jpeg?alt=media&token=04ae1a0a-5143-47c3-a0ba-d09e3e790094'
    ),
    ('Batavia Cinnamon, Cinnamon Tree', '陰香',
    '',
    'Cinnamomum burmannii (Nees & T. Nees) Blume',
    '017',
    'Native',
    0, 0, 0, 0,
    '001100000000',
    '000000000110',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=6132',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=6132',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FBatavia%20Cinnamon.jpeg?alt=media&token=e5a41f62-845c-4cad-9682-24d0bfb18e31'
    ),
    ('Brisbane Box', '紅膠木',
    'Tristania conferta R. Br.',
    'Lophostemon confertus (R. Br.) Peter G. Wilson & J. T. Waterh.',
    '199',
    'Exotic',
    0, 0, 0, 0,
    '000011100000',
    '000000011000',
    'The Taiwan Acacia and Brisbane Box can be counted as two of the most common exotic trees in Hong Kong.  Native to Australia, it has dark green leaves with smooth edges; opposite when young, alternate when mature, they rotate and aggregate on branch tops.  White flowers with numerous inconspicuous stamens appear in 5 feather-like bunches in summer.  Fruits are born in autumn as bell-shaped woody capsules that can be 2 cm large.',
    '香港外來引種植物 （exotic species） 最常見的兩種是台灣相思和紅膠木。 紅膠木原產澳洲，葉墨緑，邊緣平滑，幼苗時，葉對生，長大後變為互生，樹葉於分枝頂聚生近似輪狀。白花，雄蕊如白色羽毛，細小不起眼，果成鐘形，蒴果 （capsule）。',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FBrisbane%20Box.jpeg?alt=media&token=04fcd7bc-ef70-4ee9-b4ae-5089e7f0e8c4'
    ),
    ('Buddhist Pine, Kusamaki', '羅漢松',
    '',
    'Podocarpus macrophyllus (Thunb.) Sweet',
    'G008',
    'Native',
    0, 0, 0, 0,
    '000110000000',
    '000000011000',
    'This plant grows at a slow speed.  On the sturdy stem are strong and horizontal branches.  Evergreen with alternate, spirally arranged leaves, acute at both ends, the Buddhist pine has high ornamental values.  They used to exist in abundance at the east coast of the territory.  Yet superstition turned them into vastly profitable commercial goods.  With increasing illegally logging, they are now endangered species.  Also a dioecious plant, among the row of Buddhist Pines grown in New Asia College, some flowers in spring bear small globose fruits with a purplish fleshy receptacle.  The plant’s form of a human figure gives it the common name of "Buddhist Pine".',
    '生長緩慢，樹幹蒼勁，葉片終年深綠，甚具觀賞價值。本港東岸原有大片野生，因成為迷信商品，價高而被大量偷掘，成為高度瀕危植物。新亞種植一列羅漢松，春天開花，結小果，圓果下有托，像人型，因名羅漢松。',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FKusamaki.jpeg?alt=media&token=58306bb7-d67a-49e8-8368-60ed8e92546f'
    ),
    ('Burmese Rosewood', '紫檀',
    '',
    'Pterocarpus indicus Willd.',
    '185',
    'Exotic',
    0, 0, 0, 0,
    '011111110000',
    '000000000010',
    'A large deciduous tree, it can grow up to a height of 40 meters.  The growth is slow and one tree can age more than a hundred years.  The drooping twigs form a broad canopy of a bell shape, making the plant an excellent pavement tree.  The timber is of high quality, hard and reddish, often used to make instruments and furniture.  Flowering in summer, the slightly fragranced bloom is arranged in raceme inflorescence.  Spherical fruits are like "sunnyside-up" fried eggs, dark brown in color, usually possessing one stone inside, also dark brown in color.  On CUHK campus, one Burmese Rosewood is located in front of University Health Centre on the eastern campus; a taller one can be found on the western campus near where the stele of "Chinese University of Hong Kong" lies.',
    '高大落葉喬木，可達四十米，生長緩慢，樹齡可過百年，樹冠擴張成闊鐘形，有低垂枝條，是優良的行道樹，上好的木材。花期仲夏，總狀花序，芳香。果為圓形莢果，形似「荷包蛋」，深褐色，通常有一顆種籽在內，深褐色。校園東部，近大學診所門前有一行紫檀，校園西部近「香港中文大學」的石碑，亦有一株高大的紫檀。',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FBurmese%20Rosewood.jpeg?alt=media&token=8fc0a820-5e0d-45a3-afb2-402f6e9e5356'
    ),
    ('Camel"s Foot Tree', '宮粉羊蹄甲',
    '',
    'Bauhinia variegata L.',
    '184',
    'Exotic',
    0, 0, 0, 0,
    '001000000000',
    '000100000000',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=8337',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=8337',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FBauhinia%20variegata.jpeg?alt=media&token=623752c3-7838-439c-b769-d633e6b1a043'
    ),
    ('Camptotheca', '喜樹',
    '',
    'Camptotheca acuminata Decne.',
    '207',
    'Exotic',
    0, 0, 0, 0,
    '000011100000',
    '000000001000',
    'Native to China, this deciduous tree has spherical flowers and fruits.  Fruits, samara-like, cluster in globose heads.  Leaves are oblong-elliptic, papery and slightly puberulous (hairy).  The whole tree contains camptothecin, which is a primary material for anti-cancer and leukemia treatments.  It is presently a species under national protection (category II).',
    '原生於中國。喜樹的花和果，外形均如小球，果實為多個翅果組成小球狀。全株含喜樹鹼，有抗癌、治白血病療效，是國家二級重點保護植物。',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FCamptotheca.jpeg?alt=media&token=38c21a70-dd34-48c9-ae45-d9254dc11ac4'
    ),
    ('Candlenut Tree, Common Aleurites', '石栗',
    '',
    'Aleurites moluccana (L.) Willd.',
    '237',
    'Exotic',
    0, 0, 0, 0,
    '000111111100',
    '000000000111',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=8135',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=8135',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FCandlenut.jpeg?alt=media&token=cdd3fc35-a9ef-41cb-a307-e4d85dea39ea'
    ),
    ('Carambola', '楊桃',
    '',
    'Averrhoa carambola L.',
    '268',
    'Exotic',
    0, 0, 0, 0,
    '000011110000',
    '000000001111',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=8282',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=8282',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FCarambola.jpeg?alt=media&token=ca200d58-b5f9-4fda-bd98-1fbfe481c84d'
    ),
    ('Cerbera, Sea Mango', '海杧果',
    '',
    'Cerbera manghas L.',
    '278',
    'Native',
    0, 0, 0, 0,
    '000111111110',
    '000000111111',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=4069',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=4069',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FCerbera.jpeg?alt=media&token=087fce17-0de0-4ab5-9609-3340f6ae4776'
    ),
    ('Chinese Alangium', '八角楓',
    '',
    'Alangium chinense (Lour.) Harms',
    '206',
    'Native',
    0, 0, 0, 0,
    '000011100000',
    '000000111110',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=3369',
    'https://www.herbarium.gov.hk/en/hk-plant-database/plant-detail/index.html?pType=species&oID=3369',
    'https://firebasestorage.googleapis.com/v0/b/tree-app-c9daf.appspot.com/o/default%2FAlangium.jpeg?alt=media&token=55c7d0eb-6b1b-4a38-824b-490f6fccc553'
    )
;